tasks:
  - init: >
      touch /tmp/.npm-lock &&
      yarn install &&
      rm /tmp/.npm-lock
    command: ./.gitpod.init.sh
  - init: sleep 1 && while [ -f /tmp/.npm-lock ]; do sleep 1; done
    command: yarn start

ports:
  - port: 3000
    onOpen: open-preview